---
include:
  # Left half (central/master)
  - board: eyelash_sofle_left
    shield: nice_view
    artifact-name: eyelash_sofle_left

  # Right half (peripheral)
  - board: eyelash_sofle_right
    shield: nice_view_custom
    artifact-name: eyelash_sofle_right

  # Universal settings reset (works for all boards)
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: settings_reset
