---
include:
  # STANDARD MODE - Left central + Right peripheral

  # Left half (central/master)
  - board: eyelash_sofle_left
    shield: nice_view
    artifact-name: eyelash_sofle_left

  # Right half (peripheral)
  - board: eyelash_sofle_right
    shield: nice_view_custom
    artifact-name: eyelash_sofle_right

  # DONGLE MODE - Dongle central + Left peripheral + Right peripheral

  # Dongle (central receiver)
  - board: eyelash_sofle_dongle
    shield: nice_view
    artifact-name: eyelash_sofle_dongle

  # Left half (peripheral for dongle mode)
  - board: eyelash_sofle_left
    shield: nice_view_custom
    artifact-name: eyelash_sofle_left_peripheral

  # Right half (peripheral for dongle mode)
  - board: eyelash_sofle_right
    shield: nice_view_custom
    artifact-name: eyelash_sofle_right_peripheral

  # UNIVERSAL SETTINGS RESET

  # Universal settings reset firmware (works for all boards)
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: settings_reset
