name: Build ZMK Firmware
on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Firmware build type'
        required: true
        default: 'standard'
        type: choice
        options:
        - standard
        - dongle
        - reset-only
  push:
    branches:
      - main
    paths:
      - 'config/**'
      - 'boards/**'
      - 'zephyr/**'
      - '**.keymap'
      - '.github/workflows/build.yml'
      - 'build.yaml'
      - 'build-*.yaml'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.build_type == 'standard') && 'build-standard.yaml' || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_type == 'dongle') && 'build-dongle.yaml' || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_type == 'reset-only') && 'build-reset.yaml' || 'build.yaml' }}

  generate-pairing-info:
    runs-on: ubuntu-latest
    needs: build
    if: always() && (github.event_name != 'workflow_dispatch' || github.event.inputs.build_type != 'reset-only')
    steps:
      - uses: actions/checkout@v4

      - name: Generate Pairing Instructions
        run: |
          mkdir -p pairing-instructions

          cat > pairing-instructions/PAIRING_INSTRUCTIONS.md << 'EOF'
          # ZMK Eyelash Sofle Keyboard Pairing Instructions

          **All firmware includes ZMK Studio support by default!**

          ## Standard Mode (Left Side Master)

          1. **Flash the firmware:**
             - Left half: `eyelash_sofle_left.uf2` (master with ZMK Studio)
             - Right half: `eyelash_sofle_right.uf2` (peripheral with ZMK Studio)

          2. **Pairing process:**
             - Power on the left half first (master)
             - Power on the right half
             - They should automatically pair within 30 seconds
             - If not, press the reset button on both halves

          ## Dongle Mode (Unified Receiver)

          1. **Flash the firmware in this exact order:**
             - Dongle: `eyelash_sofle_dongle.uf2` (central with ZMK Studio)
             - Left half: `eyelash_sofle_left_peripheral.uf2` (peripheral with ZMK Studio)
             - Right half: `eyelash_sofle_right_peripheral.uf2` (peripheral with ZMK Studio)

          2. **Bonding process:**
             - Plug in the dongle to your computer
             - Power on the left half - wait for it to connect (LED will stop blinking)
             - Power on the right half - wait for it to connect
             - All three devices are now bonded!

          ## Troubleshooting

          If pairing fails:
          1. Flash the universal settings reset firmware to ALL devices:
             - Use `settings_reset.uf2` on left, right, and dongle (same file works for all)
          2. Re-flash the appropriate firmware
          3. Try the pairing process again

          ## LED Indicators
          - Blinking: Searching for connection
          - Solid: Connected
          - Off: Sleeping or battery dead

          ## Build Types Available
          - **Standard Mode**: Traditional split keyboard (left master, right peripheral)
          - **Dongle Mode**: Wireless dongle setup (central + 2 peripherals)  
          - **Reset Only**: Universal settings reset firmware for troubleshooting

          ## ZMK Studio
          All firmware includes ZMK Studio support by default - no separate "studio" versions needed!
          Connect via USB to any device to configure your keymap.
          EOF

      - name: Upload Pairing Instructions
        uses: actions/upload-artifact@v4
        with:
          name: pairing-instructions
          path: pairing-instructions/
          retention-days: 60
