name: Draw Keymap
on:
  workflow_dispatch:
  push:
    paths:
      - 'zmk-sofle-config/config/**'
      - '.github/workflows/draw.yml'
      - 'zmk-sofle-config/keymap_drawer.config.yaml'
      - 'zmk-sofle-config/keymap-drawer/**'

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      destination: "commit"
      fail_on_error: ${{ fromJSON(true) }}
